datasets:
  inflation_hicp:
    source: eurostat
    dataset_code: prc_hicp_midx
    frequency: monthly
    geography_level: country
    update_job: monthly
    used_for:
      - hidden_loss
      - trend_direction
      - cost_pressure
    filters:
      coicop: CP00
      unit: I15
      lang: en

  housing_overburden:
    source: eurostat
    dataset_code: ilc_lvho07a
    frequency: yearly
    geography_level: country
    update_job: yearly
    used_for:
      - housing_reality_check
      - relative_position
    filters:
      freq: A
      unit: PC
      incgrp: TOTAL
      age: TOTAL
      sex: T
      lang: en

  poverty_risk:
    source: eurostat
    dataset_code: ilc_li02
    frequency: yearly
    geography_level: country
    update_job: yearly
    used_for:
      - poverty_context
      - economic_security
    filters:
      freq: A
      unit: PC
      indic_il: LI_R_MD60
      sex: T
      age: TOTAL
      lang: en

  income_capacity:
    source: eurostat
    dataset_code: ilc_di03
    frequency: yearly
    geography_level: country
    update_job: yearly
    used_for:
      - income_capacity
    filters:
      freq: A
      unit: PPS
      indic_il: MED_E
      sex: T
      age: TOTAL
      lang: en

  net_earnings_capacity:
    source: eurostat
    dataset_code: earn_nt_net
    frequency: yearly
    geography_level: country
    update_job: yearly
    used_for:
      - net_earnings_capacity
    filters:
      freq: A
      currency: PPS
      estruct: NET
      ecase: P1_NCH_AW100
      lang: en

  employment_strength:
    source: eurostat
    dataset_code: lfsi_emp_a
    frequency: yearly
    geography_level: country
    update_job: yearly
    used_for:
      - employment_strength
    filters:
      freq: A
      indic_em: EMP_LFS
      sex: T
      age: Y20-64
      unit: PC_POP
      lang: en
